from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import io, os, base64, tempfile

IPROMO_NAVY  = colors.HexColor("#1B2A6B")
IPROMO_TEAL  = colors.HexColor("#00B5B8")
IPROMO_LIGHT = colors.HexColor("#F4F6F9")

def generate_pdf(req) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        rightMargin=0.5*inch, leftMargin=0.5*inch,
        topMargin=0.5*inch,   bottomMargin=0.5*inch,
    )
    story = []

    logo_path = os.path.join(os.path.dirname(__file__), "..", "assets", "ipromo_logo.png")
    header_data = []
    if os.path.exists(logo_path):
        header_data.append([Image(logo_path, width=1.8*inch, height=0.6*inch), ""])
    header_data.append([
        Paragraph(
            '<font color="#1B2A6B" size="18"><b>3D Product Mockup</b></font>',
            ParagraphStyle("h", alignment=TA_LEFT)
        ),
        Paragraph(
            '<font color="#00B5B8" size="9">iPromo — 27 Years of Branded Merchandise Excellence</font>',
            ParagraphStyle("sub", alignment=TA_LEFT)
        ),
    ])
    t = Table(header_data, colWidths=[4*inch, 3*inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), IPROMO_NAVY),
        ("TEXTCOLOR",  (0,0), (-1,0), colors.white),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [IPROMO_LIGHT]),
        ("GRID", (0,0), (-1,-1), 0, colors.white),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ("LEFTPADDING",  (0,0), (-1,-1), 8),
        ("RIGHTPADDING", (0,0), (-1,-1), 8),
        ("TOPPADDING",   (0,0), (-1,-1), 6),
        ("BOTTOMPADDING",(0,0), (-1,-1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.2*inch))

    if req.snapshot_url:
        b64 = req.snapshot_url.split(",", 1)[-1]
        img_bytes = base64.b64decode(b64)
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            tmp.write(img_bytes)
            tmp_path = tmp.name
        story.append(Image(tmp_path, width=4.5*inch, height=4.5*inch, hAlign="CENTER"))
        story.append(Spacer(1, 0.15*inch))

    detail_data = [
        ["Product Name", req.product_name],
        ["Item #",       req.item_no],
        ["Price Range",  req.price],
        ["Selected Color", req.color],
    ]
    dt = Table(detail_data, colWidths=[2*inch, 5*inch])
    dt.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (0,-1), IPROMO_NAVY),
        ("TEXTCOLOR",  (0,0), (0,-1), colors.white),
        ("BACKGROUND", (1,0), (1,-1), IPROMO_LIGHT),
        ("GRID", (0,0), (-1,-1), 0.5, colors.white),
        ("FONTNAME",  (0,0), (-1,-1), "Helvetica"),
        ("FONTSIZE",  (0,0), (-1,-1), 10),
        ("LEFTPADDING",  (0,0), (-1,-1), 10),
        ("RIGHTPADDING", (0,0), (-1,-1), 10),
        ("TOPPADDING",   (0,0), (-1,-1), 7),
        ("BOTTOMPADDING",(0,0), (-1,-1), 7),
    ]))
    story.append(dt)
    story.append(Spacer(1, 0.25*inch))

    footer_style = ParagraphStyle(
        "footer", fontSize=8, textColor=colors.grey, alignment=TA_CENTER
    )
    story.append(Paragraph(
        "Generated by iPromo 3D Configurator · www.ipromo.com · 888.994.7766",
        footer_style
    ))

    doc.build(story)
    return buffer.getvalue()
